import streamlit as st
import pandas as pd
import plotly.express as px

# --- Page Config ---
st.set_page_config(page_title="Duta Data Deliverable", layout="wide")

# --- Tabs ---
tab1, tab2, tab3, tab4 = st.tabs(["📊 Dashboard", "🗺️ Map View", "📋 Data Table", "🧠 Insights"])

# --- Dashboard Tab ---
with tab1:
    st.title("Duta Data Dashboard")

    col1, col2, col3 = st.columns(3)
    col1.metric("Total Users", "2,450", "+150")
    col2.metric("Engagement Rate", "74%", "+4%")
    col3.metric("Avg. Session Time", "3m 24s", "-12s")

    st.markdown("---")
    st.write("Welcome to the Duta Data Dashboard.")

# --- Map View Tab ---
with tab2:
    st.title("Togglas Map")

    toggle = st.radio("Toggle View", ["Option A", "Option B"], horizontal=True)
    st.write(f"Selected: {toggle}")

    # Sample dataset
    df_map = px.data.gapminder().query("year == 2007")

    # Search Bar
    search_query = st.text_input("Search for a country or location (case-insensitive):")
    if search_query:
        filtered = df_map[df_map['country'].str.contains(search_query, case=False, na=False)]
        if not filtered.empty:
            st.success(f"Found {len(filtered)} location(s) matching: {search_query}")
        else:
            st.warning("No matching location found.")
    else:
        filtered = df_map

    st.subheader("Map Visualization")
    fig = px.scatter_geo(filtered, locations="iso_alpha", color="continent",
                         hover_name="country", size="pop",
                         projection="natural earth", title="World Data Map")
    st.plotly_chart(fig, use_container_width=True)

# --- Data Table Tab ---
with tab3:
    st.title("Data Summary Table")

    sample_data = {
        "Region": ["North", "South", "East", "West"],
        "Users": [850, 650, 480, 470],
        "Growth (%)": [12.5, 9.8, 7.3, 6.9]
    }
    df = pd.DataFrame(sample_data)
    st.dataframe(df)

# --- Insights Tab ---
with tab4:
    st.title("Insights & Interpretation")

    st.info("""
    - North region has the highest growth and user base.
    - South is catching up with slightly slower growth.
    - Consider investing in East and West regions for balance.
    """)

    st.markdown("Further analysis and recommendations go here.")

# --- Footer ---
st.markdown("---")
st.caption("Generated by Duta Data · 2025")